config/routes.rb
Grubulate::Application.routes.draw do

  match 'appliances/' => 'appliances#index'
  match 'ingredients/' => 'ingredients#index'

  resources :profiles do
    resources :favorites, :only => [:index, :create, :destroy]
    resources :fans, :only => [:index]
  end

  resources :notifications, :only => [:index, :destroy]
  
  resources :recipes do
    post 'rate', :on => :member
    resources :comments, :only => [:create, :destroy, :index]
  end

  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  

   root :to => "home#index"

end

app/models/profile.rb
require 'URLTempfile'
class Profile < ActiveRecord::Base
  ajaxful_rater
  belongs_to :user
  has_many :notifications, :foreign_key => "receiver_id", :order => 'created_at DESC', :include => [:sender, :notifiable]
  has_many :unseen_notifications, :class_name => "Notification", :foreign_key => "receiver_id", :conditions => {:seen => false}, :order => 'created_at DESC', :limit => 5, :include => [:sender, :notifiable]
  has_many :recipes

  has_many :fan_relationships, :class_name => "FavoriteChef", :dependent => :destroy
  has_many :fans, :through => :fan_relationships, :source => :chef

  has_many :favorite_chefs_relationships, :class_name => "FavoriteChef", :foreign_key => :chef_id, :dependent => :destroy
  has_many :favorite_chefs, :through => :favorite_chefs_relationships, :source => :profile

  has_many :comments

  validates :username, :presence => true, :uniqueness => true, :format => /[a-zA-Z0-9_]/, :length => {:minimum => 5, :maximum => 20}
  validates :bio, :length => {:maximum => 1000}

  attr_accessible :username, :bio, :avatar
  
  #friendly url
  has_friendly_id :username
  
  #profile pic
  has_attached_file :avatar, :styles => { :small => ["150x150#", :png], :thumb => ["50x50#", :png] }

  def create_recipe(recipe)
    return false unless recipe.valid?

    recipes << recipe
  end

  def num_unseen_notifications
    Notification.count(:conditions => {:receiver_id => id, :seen => false})
  end

  def add_favorite_chef(chef)
    favorite_chefs << chef
  end

  def remove_favorite_chef(chef)
    favorite_chefs.delete(chef)
  end

  def is_a_fan_of(profile)
    favorite_chefs.include?(profile)
  end

  def url_to_image(url,save)
      self.avatar = URLTempfile.new(url)
      self.save if save
  end

  def seen_notification(id)
    notification = notifications.find(id)
    notification.seen = true
    notification.save
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, :except => :show
  def show
    @profile_displayed = Profile.find(params[:id])
    @recipes = Recipe.get_by_profile(params[:page], @profile_displayed)
  end

  def edit
    @profile = current_profile
  end

  def update
    @profile = current_profile
    if @profile.update_attributes(params[:profile])
        redirect_to(@profile)
    else
      render :action => "edit"
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_link.html.haml
=image_tag profile.avatar.url(:thumb)
= link_to profile.username, profile

app/views/profiles/edit.html.haml
= form_for(@profile, :html => { :multipart => true }) do |f|
  = form_errors(@profile)

  = f.label :bio
  = f.text_area :bio
  %p
    %strong Current Profile Picture
    =image_tag @profile.avatar.url(:small)
    %br/
    = f.label "Change Profile Picture"
    %br/
    = f.file_field :avatar
    %br/
    = f.submit "Update"


= link_to "Want to sign in with facebook? Associate your account here", user_omniauth_authorize_path(:facebook)

app/views/profiles/show.html.haml
- if @profile_displayed
  You're on
  %strong= @profile_displayed.username
  's page!
  %p
    =image_tag @profile_displayed.avatar.url(:small)
  %br/
  %strong About Me: 
  = @profile_displayed.bio
  %br/

  Number of Fans: #{@profile_displayed.fans.count}
  - if current_profile != @profile_displayed

    - if current_profile and current_profile.is_a_fan_of(@profile_displayed)
      = link_to "Not a fan", profile_favorite_path(@profile_displayed, current_profile), :method => :delete
    - else
      = link_to "Favorite this chef", profile_favorites_path(@profile_displayed), :method => :post
  = link_to "See Fans", profile_fans_path(@profile_displayed)

  %br/

  %div
    = link_to "See Favorite Chefs", profile_favorites_path(@profile_displayed)

  %div
    %strong #{@profile_displayed.username}'s Recipes
    = render :partial => "recipes/recipe_preview", :collection => @recipes, :as => :recipe

    = will_paginate @recipes
- else
  No Profile Found!

app/views/profiles/update.html.haml
%h1 Profiles#update
%p Find me in app/views/profiles/update.html.haml