config/routes.rb
Grubulate::Application.routes.draw do

  match 'appliances/' => 'appliances#index'
  match 'ingredients/' => 'ingredients#index'

  resources :profiles do
    resources :favorites, :only => [:index, :create, :destroy]
    resources :fans, :only => [:index]
  end

  resources :notifications, :only => [:index, :destroy]
  
  resources :recipes do
    post 'rate', :on => :member
    resources :comments, :only => [:create, :destroy, :index]
  end

  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  

   root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe, :counter_cache => true
  belongs_to :profile

  validates :body, :presence => true, :length => {:minimum => 3, :maximum => 1000}
  validates :recipe_id, :presence => true
  validates :profile_id, :presence => true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :except => :index
  before_filter :setup
  def index
    @comments = @recipe.comments
  end

  def create
    comment = @recipe.add_comment(params[:comment].merge({:profile_id => current_profile.id}))
    if !comment.valid?
      flash[:invalid_comment] = comment
    end
    redirect_to @recipe
  end

  def destroy
    comment = @recipe.comments.find(params[:id], :conditions => {:profile_id => current_profile.id})
    comment.destroy
    redirect_to @recipe
  end

  private
  def setup
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
=render "profiles/link", :profile => comment.profile 
posted:
- if comment.profile == current_profile
  = link_to " - Delete", recipe_comment_path(comment.recipe, comment), :confirm => "are you sure?", :method => :delete
%div
  #{simple_format(comment.body)}

app/views/comments/_form.html.haml
= form_for flash[:invalid_comment] || @comment, :url => recipe_comments_path(@recipe)  do |f|
  = form_errors(flash[:invalid_comment] || @comment)
  %p
    = f.label :body
    = f.text_area :body
  %p
    = f.submit
  

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/destroy.html.haml
%h1 Comments#destroy
%p Find me in app/views/comments/destroy.html.haml

app/views/comments/index.html.haml
%div
  %strong Comments for:
  = render :partial => "recipes/recipe_preview", :object => @recipe, :as => :recipe


%br/
%br/
%div
  %strong Comments
  %br/
  = render @comments