config/routes.rb
Grubulate::Application.routes.draw do

  match 'appliances/' => 'appliances#index'
  match 'ingredients/' => 'ingredients#index'

  resources :profiles do
    resources :favorites, :only => [:index, :create, :destroy]
    resources :fans, :only => [:index]
  end

  resources :notifications, :only => [:index, :destroy]
  
  resources :recipes do
    post 'rate', :on => :member
    resources :comments, :only => [:create, :destroy, :index]
  end

  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  

   root :to => "home#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  ajaxful_rateable :stars => 5, :cache_column => :rating_average
  cattr_reader :per_page
  @@per_page = 20

  validates :title, :presence => true
  validates :cook_time, :presence => true, :numericality => {:only_integer => true, :greater_than_or_equal_to => 0}
  validates :short_desc, :presence => true, :length => {:minimum => 5, :maximum => 255}
  validates :instructions, :presence => true, :length => {:minimum => 5, :maximum => 5000}
  validates :difficulty, :presence => true, :numericality => {:only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5}

  belongs_to :profile
  has_many :meals
  has_many :entrees, :through => :meals

  has_many :foods
  has_many :ingredients, :through => :foods

  has_many :equipments
  has_many :appliances, :through => :equipments

  has_many :comments, :dependent => :destroy, :include => [:profile, :recipe]
  has_many :most_recent_comments, :class_name => 'Comment', :order => 'created_at DESC', :limit => 10, :include => [:profile, :recipe]

  validates :ingredients, :presence => true

  attr_accessible :title, :short_desc, :instructions, :difficulty, :cook_time, :entree_ids, :ingredient_ids, :appliance_ids

  def add_ingredient(ingr)
    ingredients << ingr
  end

  def ingredientsNames
    ingredients.map{|e| e.name}.join(', ')
  end

  def appliancesNames
    appliances.map{|e| e.name}.join(', ')
  end

  def add_comment(attrs)
    if !attrs.is_a?(Hash)
      return false
    end
    comments.create(attrs)
  end


  def remove_comment(comment)
    comments.delete(comment)
  end

  class << self
    
    #TODO
    # Default will be called by default browse
    #def search(page)
    #  paginate :page => page, :order => "created_at DESC"
    #end

    def get_by_profile(page, profile)
      paginate :page => page, :order => "created_at DESC", :conditions => ["recipes.profile_id = ?", profile.id], :include => [:profile]
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  def index

    params[:search]["ingredients_name_equals_any"] = params[:ingredients].strip.split(',').map{|e| e.strip} if params[:ingredients]
    params[:search]["appliances_name_equals_any"] = params[:appliances].strip.split(',').map{|e| e.strip} if params[:appliances]
    
    flash[:search_ingredients] = params[:ingredients].strip if params[:ingredients]
    flash[:search_appliances] = params[:appliances].strip if params[:appliances]
    @search = Recipe.search(params[:search])
    pagination_args = {:page => params[:page], :include => [:profile]}
    pagination_args[:order] = "recipes.created_at DESC" if !(params[:search] && params[:search][:meta_sort])
    @recipes = @search.relation.select("DISTINCT(recipes.id), recipes.*").paginate pagination_args

  end

  def show
    @recipe = Recipe.find(params[:id], :include => :most_recent_comments)
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
    @entrees = Entree.all
  end

  def create
    params[:recipe][:entree_ids] ||= []
    params[:ingredients] ||= ""
    params[:appliances] ||= ""
    params[:recipe][:appliance_ids] = Appliance.names_to_ids(
      params[:appliances].strip.split(',').map{|e| e.strip}
    )
    params[:recipe][:ingredient_ids] = Ingredient.names_to_ids(
      params[:ingredients].strip.split(',').map{|e| e.strip}
    )
    @recipe = Recipe.new(params[:recipe])
    @recipe.cook_time.to_i
    if current_profile.create_recipe(@recipe)
      redirect_to(@recipe)
    else
      @entrees = Entree.all
      flash[:entrees] = params[:recipe][:entree_ids]
      flash[:ingredients] = params[:ingredients].strip
      flash[:appliances] = params[:appliances].strip
      render :action => :new
    end
  end

  def edit
    @recipe = current_profile.recipes.find(params[:id])
    @entrees = Entree.all
  end

  def update
    params[:recipe][:entree_ids] ||= []
    params[:ingredients] ||= ""
    params[:appliances] ||= ""
    params[:recipe][:appliance_ids] = Appliance.names_to_ids(
      params[:appliances].strip.split(',').map{|e| e.strip}
    )
    params[:recipe][:ingredient_ids] = Ingredient.names_to_ids(
      params[:ingredients].strip.split(',').map{|e| e.strip}
    )

    @recipe = current_profile.recipes.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to(@recipe)
    else
      @entrees = Entree.all
      flash[:ingredients] = params[:ingredients].strip
      flash[:appliances] = params[:appliances].strip
      flash[:entrees] = params[:recipe][:entree_ids]
      render :action => "edit"
    end
  end

  def destroy
    @recipe = current_profile.recipes.find(params[:id])
    @recipe.destroy

    redirect_to(recipes_path)
  end

  def rate
    @recipe = Recipe.find(params[:id])
    @recipe.rate(params[:stars], current_profile)
    #render do |page|
      #render :text => ratings_for(@recipe).to_yaml
     # page.replace_html @recipe.wrapper_dom_id(params), ratings_for(@recipe, params.merge(:wrap => false))
     # page.visual_effect :highlight, @recipe.wrapper_dom_id(params)
    #end
    
  end

  private

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.haml
= form_for setup_recipe(@recipe) do |f|
  = form_errors(@recipe)
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :difficulty
    = select("recipe", "difficulty", (1..5).each{|e| e})
  %p
    = f.label :entree
    - for entree in @entrees
      = label(:entree, entree.name)
      = check_box_tag "recipe[entree_ids][]", entree.id, recipe_in_entree?(@recipe, entree) || (!flash[:entrees].nil? && flash[:entrees].include?(entree))
      

  %p
    = f.label :cook_time
    = f.text_field :cook_time

  =label(:ingredient, "Ingredients")
  .ui-widget
    %input{:id => :ingredients, :name => :ingredients , :size => 50, :value => @recipe.ingredientsNames ? @recipe.ingredientsNames : (!flash[:ingredients].nil? ? flash[:ingredients] : "")}
  =label(:ingredient, "Appliances")
  .ui-widget
    %input{:id => :appliances, :name => :appliances , :size => 50, :value => @recipe.appliancesNames ? @recipe.appliancesNames : (!flash[:appliances].nil? ? flash[:appliances] : "")}
  
  %p
    = f.label "Short Description"
    = f.text_area :short_desc
  %p
    = f.label :instructions
    = f.text_area :instructions
  %p
    = f.submit

app/views/recipes/_rate_recipe.html.haml
%div[recipe, :rate]
  %strong Rating:
  - static ||= nil
  - if static
    = ratings_for recipe, :static
  - else
    = ratings_for recipe

app/views/recipes/_recipe.html.haml
%div
  %strong= link_to recipe.title, recipe
  - if recipe.profile == current_profile
    = link_to " - Edit", edit_recipe_path(recipe)
    = link_to " - Delete", recipe_path(recipe), :confirm => "are you sure?", :method => :delete
  %i
    by:

    =render "profiles/link", :profile => recipe.profile 
  %br
  = render "rate_recipe", :recipe => recipe
  %br
  Difficulty: #{recipe.difficulty}
  %br
  Entrees:
  - for entree in recipe.entrees
    #{entree.name}

  %div
    Ingredients:
    - for ingredient in recipe.ingredients
      #{ingredient.name}

  %div
    Appliances:
    - for appliance in recipe.appliances
      #{appliance.name}

  %br
  Short Description: #{recipe.short_desc}
  %br
  Cook Time: #{recipe.cook_time}
  %br
  %strong Instructions
  %p
    #{simple_format(recipe.instructions)}

app/views/recipes/_recipe_preview.html.haml
%div
  %strong= link_to recipe.title, recipe
  %br
  Difficulty: #{recipe.difficulty}
  %br
  = render :partial => "recipes/rate_recipe", :object => recipe, :as => :recipe, :locals => {:static => true}
  %br
  Short Description: #{recipe.short_desc}
  %i
    =render "profiles/link", :profile => recipe.profile

app/views/recipes/create.html.haml
%h1 Recipes#create
%p Find me in app/views/recipes/create.html.haml

app/views/recipes/destroy.html.haml
%h1 Recipes#destroy
%p Find me in app/views/recipes/destroy.html.haml

app/views/recipes/edit.html.haml
- content_for :head do
  = javascript_include_tag "autocomplete-recipe"



= render 'form'

app/views/recipes/index.html.haml
- content_for :head do
  = javascript_include_tag "autocomplete-recipe"


%strong Search Recipes:
= form_for @search do |f|

  =label(:ingredient, "Ingredients")
  .ui-widget
    %input{:id => :ingredients, :name => :ingredients , :size => 50, :value => (!flash[:search_ingredients].nil? ? flash[:search_ingredients] : "")}
  =label(:ingredient, "Appliances")
  .ui-widget
    %input{:id => :appliances, :name => :appliances , :size => 50, :value => (!flash[:search_appliances].nil? ? flash[:search_appliances] : "")}
  

  
  =f.label "Difficulty Range from"
  = f.text_field :difficulty_gte, :size => 8
  = f.label :difficulty_lte, "to"
  = f.text_field :difficulty_lte, :size => 8

  %br/
  =f.label "Cook Time Range from"
  = f.text_field :cook_time_gte, :size => 8
  = f.label :cook_time_lte, "to"
  = f.text_field :cook_time_lte, :size => 8


  %br/
   
  =f.label "Entree Types"
  - f.collection_checks :entrees_id_in, Entree.all, :id, :name do |check|
    = check.box
    = check.label
    
  %br/
  =f.submit

%strong Recipes:
= link_to "Create new recipe", new_recipe_path

%div
  %strong Sort By:
  = sort_link @search, :rating_average, "Rating"
  | 
  = sort_link @search, :comments_count, "Comments"
= render :partial => "recipe_preview", :collection => @recipes, :as => :recipe

= will_paginate @recipes

app/views/recipes/new.html.haml
- content_for :head do
  = javascript_include_tag "autocomplete-recipe"



= render :partial => 'form'

app/views/recipes/rate.js.erb
$("div #rate_recipe_<%= @recipe.id %>").html("<%= escape_javascript(render("rate_recipe", :recipe => @recipe)) %>");

app/views/recipes/show.html.haml
= render @recipe
= render 'comments/form'
= render @recipe.most_recent_comments
= link_to "View all comments for this recipe", recipe_comments_path(@recipe)

app/views/recipes/update.html.haml
%h1 Recipes#update
%p Find me in app/views/recipes/update.html.haml