config/routes.rb
Grubulate::Application.routes.draw do

  match 'appliances/' => 'appliances#index'
  match 'ingredients/' => 'ingredients#index'

  resources :profiles do
    resources :favorites, :only => [:index, :create, :destroy]
    resources :fans, :only => [:index]
  end

  resources :notifications, :only => [:index, :destroy]
  
  resources :recipes do
    post 'rate', :on => :member
    resources :comments, :only => [:create, :destroy, :index]
  end

  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  

   root :to => "home#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, :polymorphic => true
  belongs_to :sender, :foreign_key => "sender_id", :class_name => "Profile"
  belongs_to :receiver, :foreign_key => "receiver_id", :class_name => "Profile"
  validates :sender_id, :presence => true
  validates :receiver_id, :presence => true
  validates :notifiable_id, :presence => true
  validates :notifiable_type, :presence => true


  class << self
    def add(notifiable, sender=nil, receiver = nil)
      if notifiable.is_a?(Comment)
        sender ||= notifiable.profile
        receiver ||= notifiable.recipe.profile
      elsif notifiable.is_a?(Recipe) 
        sender ||= notifiable.profile
        receiver ||= notifiable.profile.fans
      end

      attrs = {:sender => sender, :receiver => receiver, :notifiable => notifiable, 
               :notifiable_type => notifiable.class.to_s}

      if receiver.is_a?(Array)
        receiver.each{|r| create_notification(attrs.merge(:receiver => r)) }
      else
        create_notification(attrs)
      end
    end

    def create_notification(args)
      create(args)
    end

    def method_missing(meth, *args, &blk)
      if meth.to_s =~ /^add_(comment|recipe)$/
        add(*args, &blk)
      else
        super
      end
    end

    def respond_to?(meth, include_private = false)
      if meth.to_s =~ /^add_(comment|recipe)$/
        true
      else
        super
      end
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!
  def index
    if params[:type] == "all"
      @notifications = current_profile.notifications
    else
      @notifications = current_profile.unseen_notifications
    end
  end

  def destroy
    current_profile.seen_notification(params[:id])
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_comment_notification.html.haml
%strong 
  = link_to notification.sender.username, notification.sender
added a new comment on your recipe,
%strong 
  =link_to notification.notifiable.recipe.title, notification.notifiable.recipe
!

app/views/notifications/_notification.html.haml
- html_attrs = {}
- inline ||= nil
- if inline
  - html_attrs[:style] = "display: inline;"
  
.notification{html_attrs}
  =render :partial => "notifications/#{notification.notifiable_type.downcase}_notification", :object => notification, :as => :notification
  - if !notification.seen
    = link_to "- X", notification_path(notification), :confirm => "are you sure?", :method => :delete

app/views/notifications/_recipe_notification.html.haml
%strong 
  = link_to notification.sender.username, notification.sender
created a new recipe called
%strong 
  =link_to notification.notifiable.title, notification.notifiable
!

app/views/notifications/destroy.html.haml
%h1 Notifications#destroy
%p Find me in app/views/notifications/destroy.html.haml

app/views/notifications/index.html.haml
#notification-nav
  - if !current_page?(:type => "all")
    Unseen Notifications
  - else
    = link_to "Unseen Notifications", notifications_path 
  |
  - if current_page?(:type => "all")
    All Notifications
  - else
    = link_to "All Notifications", notifications_path(:type => "all")

%strong Notifications:
- if @notifications == [] #empty? throws a polymorphic error... what.
  %p No Notifications
- else
  =render @notifications, :locals => {:delete => true}